- name: ansible playbook example to fetch the variables from inventory
  hosts: localhost
  tasks:
  - name: printing the variables 
    ansible.builtin.debug:
      msg: "My name is {{Name}} and i am working in {{Company}}"